# Generated by Django 5.2.4 on 2025-10-31 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdetail')),
                ('raw_materials', models.ManyToManyField(to='product.rawmaterial')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
