# Generated by Django 5.2.4 on 2025-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategory_is_active_productdetail_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
