# Generated by Django 5.2.4 on 2025-11-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcategory_code_alter_productdetail_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='The classification group this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.ForeignKey(help_text='Specific product variant (SKU) details and specifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Marketing name or common product identifier (optional).', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(help_text='List of raw materials and components required for this product.', to='product.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(help_text="Unique category identifier (e.g., 'APP-MEN', 'ELEC-SMARTPHONE').", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(help_text="Human-readable category name for display and selection (e.g., 'Men's Apparel').", max_length=120),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this category from selection in new products (retains historical data).'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='code',
            field=models.CharField(help_text="Unique product variant code (SKU). Example: 'IPHONE14-BLK-128'.", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.CharField(help_text='Detailed specification or variant description (e.g., size, color, model year).', max_length=120),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls if this product detail is available for new product creation.'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(help_text="Unique identifier for inventory tracking (e.g., 'COTTON-100PCT', 'STEEL-GA16').", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='description',
            field=models.CharField(help_text='Detailed description of the material, grade, or composition.', max_length=120),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the material is currently available for new product formulations.'),
        ),
    ]
