# Generated by Django 5.2.4 on 2025-10-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationbody',
            options={'verbose_name_plural': 'Certification Bodies'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='supplychaincompany',
            options={'verbose_name_plural': 'Supply Chain Companies'},
        ),
    ]
