# Generated by Django 5.2.4 on 2025-11-01 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_certificationbody_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(help_text='Street address line 1 (Required).', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='City or town name (Required).', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Country name (Required).', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(help_text='State, province, or region (Required).', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(help_text='Postal code or ZIP code (Required).', max_length=120),
        ),
        migrations.AlterField(
            model_name='certificationbody',
            name='address',
            field=models.ForeignKey(help_text='The official business address of the certification body.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
        migrations.AlterField(
            model_name='certificationbody',
            name='name',
            field=models.CharField(help_text='The full name of the certification or standards organization.', max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(help_text='The primary physical address of the company.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='The official legal name of the company.', max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(help_text="Django users who have access permissions for this company's data.", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplychaincompany',
            name='address',
            field=models.ForeignKey(help_text='The business location of the supply chain partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
        migrations.AlterField(
            model_name='supplychaincompany',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Check if this partner has been approved and validated for certification processes.'),
        ),
        migrations.AlterField(
            model_name='supplychaincompany',
            name='name',
            field=models.CharField(help_text='The legal name of the supply chain partner.', max_length=120),
        ),
    ]
