# Generated by Django 5.2.4 on 2025-11-04 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_address_alter_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number for the customer.', max_length=20, null=True)),
                ('company', models.ForeignKey(help_text='The company this customer user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='customer.company')),
                ('user', models.OneToOneField(help_text='The Django user account associated with this customer profile.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['company', 'user__username'],
            },
        ),
    ]
