# Generated by Django 5.2.4 on 2025-11-01 09:24

import application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=application.models.application_file_path),
        ),
        migrations.CreateModel(
            name='ApplicationCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='application.application')),
            ],
            options={
                'verbose_name': 'Application Company Info (Staging)',
                'verbose_name_plural': 'Application Company Info (Staging)',
            },
        ),
        migrations.CreateModel(
            name='ApplicationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_chain_partner_name_raw', models.CharField(blank=True, max_length=120, null=True)),
                ('product_name', models.CharField(blank=True, max_length=120, null=True)),
                ('product_category', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_materials_list', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='application.application')),
            ],
            options={
                'verbose_name': 'Application Product (Staging)',
                'verbose_name_plural': 'Application Products (Staging)',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSupplyChainPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_partners', to='application.application')),
            ],
            options={
                'verbose_name': 'Application Supply Chain Partner (Staging)',
                'verbose_name_plural': 'Application Supply Chain Partners (Staging)',
            },
        ),
    ]
