# Generated by Django 5.2.4 on 2025-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
