# Generated by Django 5.2.4 on 2025-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this bulk submission', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of this submission', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('success', 'Success'), ('fail', 'Fail')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information', null=True)),
            ],
            options={
                'verbose_name': 'Bulk Submission',
                'verbose_name_plural': 'Bulk Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='bulk_submissions',
            field=models.ManyToManyField(blank=True, related_name='applications', to='application.bulksubmission'),
        ),
    ]
