# Generated by Django 5.2.4 on 2025-11-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_bulksubmission_application_bulk_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bulk_submissions',
        ),
        migrations.AddField(
            model_name='application',
            name='bulk_submissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.bulksubmission'),
        ),
    ]
